services:
  db:
    image: mysql:8.0
    container_name: bd_livro_container
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
    driver: local